# To Do

  * Update TO DO regularly
  * **Revisit outlier correction**. We are using cumulative probability to detect measurement errors/outliers, but this is not giving us the density. We should use the quantile functions to determine the space that contains 99% of the probability mass, and then ask, are the point outside of that region.
  * Edits to text
    * anticipate main points in both introduction and discussion - inherent in many of the suggested accounts, a bunch of assumptions that follow much of the literature but may affect the results.
    * add categorization accuracy results from Eklund & Traunmuller (1997): for phonated vowels produced by female talkers 94.7% (10 listeners).
  
## Points for when reviews are back
  * The neural correlates of intrinsic and extrinsic accounts, and their relative effectiveness (e.g., johnson-sjerps2021)

## To work on while in review:
  * Formant transitions - how much information is there in there and does it change the ranking of normalization accounts if those are considered? Check this by including F1-F4 values at the start and end points in the trajectory in the IOs. Potentially include F4 as well, as Barreda said it contained important information.
  * Can we address the concern that the fact that we only have female talkers might underestimate the performance of some, in particular uniform scaling, accounts. One idea would be to generate fake male talkers by multiplying formants by .8 (15-20% height diff), and lowering f0 by one octave, and then conduct same analyses over combined data of real female and fake male talkers. In interpreting any differences in results this might cause, keep in mind that this approach generates the fake male talkers under the assumption of uniform scaling (still, it's going to be informative how much the performance of the unnormalized decreases).
  * fig 10: color labels, or only label a few vowels (or none).
  
## To-Do during revision 1
  * Moving study 1 to SI: should any visualizations of the vowel space after normalization be included in the main text?
